### ISSUE TITLE
Korjaa gemfile

### ISSUE THREAD

**Issue by LofhJann** [tkt-lapio/tkt-lapio.github.io#21]
time.rb:31:in `block in setup'
/home/janne/.gem/ruby/2.6.0/gems/bundler-1.16.2/lib/bundler/runtime.rb:313:in `check_for_activated_spec!': You have already activated ffi 1.10.0, but your Gemfile requires ffi 1.9.25. Prepending `bundle exec` to your command may solve this. (Gem::LoadError)

**Comment by LofhJann** [comment]
bundle exec on oikea tapa tehdä tämä, suljetaan koska ohjeet näyttäisi olevan jo korjattu
